### ISSUE TITLE
Project.registerOpener is deprecated.

### ISSUE THREAD

**Issue by hiyenwong** [rgbkrk/atom-python#8] opened 2014-11-29 04:02 UTC
Use Workspace::registerOpener instead

```
Project.registerOpener (/opt/atom/resources/app/src/project.js:467:7)
Object.activate (/home/dexter/.atom/packages/python/lib/python.coffee:10:20)
Package.activateNow (/opt/atom/resources/app/src/package.js:163:27)
<unknown> (/opt/atom/resources/app/src/package.js:149:28)
Package.measure (/opt/atom/resources/app/src/package.js:95:15)
Package.activate (/opt/atom/resources/app/src/package.js:143:14)
PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:109:21)
PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:98:14)
PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:85:19)
Atom.startEditorWindow (/opt/atom/resources/app/src/atom.js:373:21)
Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:14:8)
Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:20:4)
Module._compile (module.js:455:26)
Object..js (module.js:473:10)
Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
Function.Module._load (module.js:311:12)
Module.require (module.js:363:17)
require (module.js:379:17)
window.onload (file:///opt/atom/resources/app/static/index.js:20:25)
```

**Comment by rgbkrk** [comment] 2014-11-29 17:34
Please use [atom-script](https://github.com/rgbkrk/atom-script), which is the more generic version of this package that is up to date. It has support for pretty much every language with a REPL (and some that don't).

Duplicate of #4.

**Closed as completed by rgbkrk** 2014-11-29 17:34 UTC
